### ISSUE TITLE
R6 Checklist of Items

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-reveal#1126]
- [ ] Get sign off from CHAI on configurable form workflow

- [ ] Make sure tasks generation in Java code generate as expected for FI, MDA, and IRS workflows in OpenSRP server

- [ ] If there’s a form configuration it is reflected in the Android app

- [ ] Some bugs need to be triaged and fixed (Akros testing LS to share list)

- [ ] Dynamic tasking documentation to be developed

- [ ] Train CHAI, VW and Akros in how to use Superset Schedule a training

- [ ] Develop Documentation on the Jurisdiction Metadata Load

- [ ] C5 Series usage analytics (Acceptance Criteria coming Monday 25th Oct)
